name: 'Submit to Web Store'

#Documentation for secrets: https://github.com/PlasmoHQ/bms/blob/main/tokens.md

on:
  workflow_dispatch:

jobs:
  main:
    name: Build and publish
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install packages
        run: npm ci

      - name: Build and package extension
        run: npm run build --target=chrome-mv3 --zip && npm run build --target=firefox-mv3 --zip

      - name: Publish extension
        uses: PlasmoHQ/bpp@v3
        with:
          keys: ${{ secrets.SUBMIT_KEYS }}
          chrome-artifact: build/chrome-mv3-prod.zip
          firefox-artifact: build/firefox-mv3-prod.zip
