name: Type Check

on: push

jobs:
  main:
    name: Run Typescript check
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install packages
        run: npm install

      - name: Run type check
        run: npm run type-check
